### ISSUE TITLE
Cannot get to compile against Genome2d SWC

### ISSUE THREAD

**Issue by greysondn** [FlixelCommunity/flixel#227]
There is just an "error:null" immediately after loading the configuration file if I try to compile. If I remove the Genome2d SWC from my library, things go back to "normal" - the endless list of errors I get, including ones from Genome2d missing.

I am going to try updating FlashDevelop but I don't think that's the issue. I'm fairly up to date.

Edit: This is against the most current dev mark.

**Comment by Dovyski** [comment]
I experienced that problem with FlashDevelop after it was upgraded to 4.7. I solved the problem by using the "Clean project" command before compiling anything. I don't think that's a Flixel issue, but a FlashDevelop one.

What version of Genome2d are you using?

**Comment by greysondn** [comment]
I believe it was the current from here:

https://github.com/pshtif/Genome2D/tree/master/bin

Is there a specific one that's meant to be built against?

**Comment by Dovyski** [comment]
The new GPU render has been tested with Genome2D 1.0.274. After release 1.0.279, the API has changed, so Flixel Community should build just fine against it, but it will show a black screen in GPU mode. There is a [pull request](https://github.com/FlixelCommunity/flixel/pull/225) with a fix to make everything work with 1.0.279.

The "error:null" problem seems to be a [SDK/FlashDevelop](http://www.flashdevelop.org/community/viewtopic.php?f=6&t=8611) issue though.

**Comment by greysondn** [comment]
Two things that may be involved that I've found, still chipping away at this as I work on everything else.

First, the FPT test suite carries a copy of Flixel 2.55 and of 2.56 in its default configuration, which may have been a piece of the puzzle. So I've removed both of those so I can work with it against the current marker.

Second, this may be an upstream error but if you say that there is a version that is known to be good then I should test against that before submitting it upstream.

http://stackoverflow.com/questions/6483692/flashdevelop-halted-with-no-explicit-compile-error

If nothing else, this error is teaching me just how dependent we become on compiler vomit to clue us to what's going on. I'm afraid with no error I'm at a bit of a loss. If there's a way to force it to tell me some gist of what's actually wrong here, it'd be useful.

The IDE and SDK are both up to date. I've tried cleaning. Obsessively as I move things around and search the source trees for possible answers.

**Comment by Dovyski** [comment]
I've just merged the pull request I mentioned. The dev branch should now work with Genome2D 1.0.279.

About the FPT compilation, I've tried a different approach. I cloned the [FlixelSandbox](https://github.com/FlixelCommunity/FlixelSandbox) project and moved the FPT folders `src` and `lib` into it. The FlixelSandbox project seems to compile and inform compilation erros correctly.

You could try that and see how it goes.

**Comment by greysondn** [comment]
No luck, though I think it's just me struggling with something that actually is simple here given that flixel itself is precompiled in that project.

I need to start on my own work. Therefore I have decided to work from the last commit I can get to compile. Ironically, this happens to be [7232E06F](https://github.com/FlixelCommunity/flixel/tree/7232e06ff9536aba45c91061eea5b1e5371b9570)

If there is anything I am able to do that may help you diagnose this error, please let me know. Naturally, the FPT will be against that commit. The good news is that the lib-dev folder is marked at ten months ago (as I write this) for last change (in FlixelSandbox) and the indicated commit is approximately seven months - in theory newer commit than even what I was pointed at? The bad news is that this is still the early side of the GPU render changes.

I imagine you're as frustrated as I am.

**Comment by Dovyski** [comment]
Go ahead and work against [7232E06F](https://github.com/FlixelCommunity/flixel/tree/7232e06ff9536aba45c91061eea5b1e5371b9570). Even though it is behind the GPU render, it should be straightforward to apply all GPU-related changes later, since there is minor API changes.

Regarding your problem, could you please ZIP your current working dir (including the FlashDevelop project file) and host it anywhere I can download? From there I can replicate your dev environment and dig for the problem.

**Comment by greysondn** [comment]
Good (bad?) news! I can compile against that SWC now. I think my current problem is related to trying to forcedebugger but once that gets cleaned up and I can confirm that compilation runs against this fine for latest dev, this can be closed.

This is in anticipation on trying to get some minor work on flixel itself done.

Edit: Genome2D_1_0_279.swc is the one referenced here and the one build works against. I'm sure dev already knows but just in case someone comes across this and wonders.

**Comment by greysondn** [comment]
Followup - despite the fact that this works, no objects seem to be drawn to camera in more complex situations.

I use factories to simplify creation. I'm befuddled.

I'm open to zipping the project up and sending it to you privately to analyze. We've moved to "won't compile" to "utterly WTF", which is an improvement but still not a useful state :disappointed:

**Comment by Dovyski** [comment]
I've seen that pattern already, but I cannot do much without analyzing the code. If you are ok sending it to me privately, that would be great. You can use dovyski@gmail.com.

**Comment by greysondn** [comment]
Subject: `flixel-community #227 code`

Sent roughly five minutes before this comment. Don't forget to check your spam filter.

Best of wishes and don't be afraid to ask me if there's something you think I could clear up or could help you with.
